version: '3'

services:
#  proxy:
#    build: nginx/
#    ports:
#      - "88:80"
#    networks:
#      - newui

  templates:
    image: portainer/templates
    networks:
      - newui

  portainer:
    image: portainer/portainer
    command: --templates http://templates/templates.json
    networks:
      - newui
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

networks:
  newui:
