version: '3'

services:
  proxy:
    build: nginx/
    ports:
      - "80:80"
    networks:
      - ui

  templates:
    image: portainer/templates
    networks:
      - ui

  portainer:
    image: portainer/portainer
    command: --templates http://templates/templates.json
    networks:
      - ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  networks:
    ui:
